export const THEMES = {
  MILITARY: {
    id: 'MILITARY',
    name: 'MİLİTER',
    description: 'Klasik savaş odası',
    bg: '#0a0e14',
    bgCard: '#111318',
    bgInput: '#0a0e14',
    border: '#1e2028',
    borderHover: '#2a2d35',
    accent: '#d4a843',
    accentDark: '#b8912e',
    accentGlow: '#d4a84320',
    textPrimary: '#e8e6e3',
    textSecondary: '#9ca3af',
    textMuted: '#6b7280',
    green: '#4a9d5b',
    red: '#c44536',
    blue: '#5b8fd4',
    fontDisplay: "'Orbitron', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    accessTitle: 'CALLSIGN GİR',
    accessWelcome: null,
  },

  CYBER: {
    id: 'CYBER',
    name: 'SİBER',
    description: 'Neon & dijital',
    bg: '#080b0f',
    bgCard: '#0d1117',
    bgInput: '#080b0f',
    border: '#1a2035',
    borderHover: '#243050',
    accent: '#00d4ff',
    accentDark: '#0099cc',
    accentGlow: '#00d4ff20',
    textPrimary: '#e0f4ff',
    textSecondary: '#7ab8cc',
    textMuted: '#3d6070',
    green: '#00ff88',
    red: '#ff3366',
    blue: '#4488ff',
    fontDisplay: "'Orbitron', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    accessTitle: 'SİSTEME ERİŞ',
    accessWelcome: null,
  },

  STEALTH: {
    id: 'STEALTH',
    name: 'STEALTH',
    description: 'Gölge operasyon',
    bg: '#050505',
    bgCard: '#0a0a0a',
    bgInput: '#050505',
    border: '#141414',
    borderHover: '#1e1e1e',
    accent: '#c0c0c0',
    accentDark: '#909090',
    accentGlow: '#c0c0c010',
    textPrimary: '#d0d0d0',
    textSecondary: '#707070',
    textMuted: '#404040',
    green: '#5a8a5a',
    red: '#8a3a3a',
    blue: '#3a5a8a',
    fontDisplay: "'Orbitron', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    accessTitle: 'TARAMA BAŞLAT',
    accessWelcome: null,
  },

  KAM: {
    id: 'KAM',
    name: 'KAM',
    description: 'Yapay zeka protokolü',
    bg: '#0a0000',
    bgCard: '#110000',
    bgInput: '#0a0000',
    border: '#2a0a0a',
    borderHover: '#3a1010',
    accent: '#cc0000',
    accentDark: '#990000',
    accentGlow: '#cc000020',
    textPrimary: '#e8e0e0',
    textSecondary: '#9a8080',
    textMuted: '#5a4040',
    green: '#8a4a4a',
    red: '#ff2200',
    blue: '#8a6060',
    fontDisplay: "'Orbitron', sans-serif",
    fontMono: "'JetBrains Mono', monospace",
    accessTitle: 'KİMLİK DOĞRULAMA',
    accessWelcome: 'HOŞ GELDİN BAŞKAN',
    isKAM: true,
  },
};

export const DEFAULT_THEME = 'MILITARY';
